version: '3.8'

services:
  # Servidor Web Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "${NGINX_PORT}:80"
      - "3003:3003"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/joomla.conf:/etc/nginx/conf.d/joomla.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  # PHP-FPM 8.2
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      - DB_HOST=mysql
      - DB_NAME_WP=${DB_NAME_WP}
      - DB_NAME_JOOMLA=${DB_NAME_JOOMLA}
      - DB_NAME_HUBSPOT=${DB_NAME_HUBSPOT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HUBSPOT_API_KEY=${HUBSPOT_API_KEY}
    depends_on:
      - mysql
    networks:
      - app-network

  # MySQL 8.0
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME_WP}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs/mysql:/var/log/mysql
    networks:
      - app-network

  # phpMyAdmin para administración de DB
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge